[package]
name = "pypackages"
version = "0.0.1"
authors = ["David O'Connor <david.alan.oconnor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "^1.1.9"
semvar = "^0.9.0"
serde = {version = "^1.0.92", features = ["derive"]}
structopt = "^0.2.18"
#text_io = "^0.1.7"
toml = "^0.5.1"